image: docker:17.04
services:
  - docker:dind
stages:
  - build
  - review
  - staging
  - production
build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG"
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker
review:
  stage: review
  image: docker:17.04
  type: deploy
  environment:
    name: review/$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    url: http://web.$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG.staging.notch8network.com
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=staging
    - export TAG=$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    - export SITE_URI=web.$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG.staging.notch8network.com
    - ./rancher-v0.4.1/rancher up -p -d -u -c -s $TAG -f docker-compose-ci.yml
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker
    - mysql
stop_review:
  stage: review
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=staging
    - ./rancher-v0.4.1/rancher rm $CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    action: stop
staging:
  stage: staging
  type: deploy
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=staging
    - export TAG=tctrac-master
    - export SITE_URI=staging.tctrac.com
    - ./rancher-v0.4.1/rancher up -p -d -u -c -f docker-compose-ci.yml --stack $CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
  when: manual
  only:
    - master
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker
production:
  stage: production
  type: deploy
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=production
    - export TAG=tctrac-master
    - export SITE_URI=www.tctrac.com
    - ./rancher-v0.4.1/rancher up -p -d -u -c -f docker-compose-prod.yml
  when: manual
  only:
    - master
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker

