image: jekyll/jekyll:latest
services:
  - docker:dind

stages:
  - review
  - staging
  - production

variables:
  DOCKER_DRIVER: overlay
  REGISTRY_HOST: registry.gitlab.com
  REGISTRY_URI: TODO/goldenseal-docs
  SITE_URI_BASE: TODO

before_script:
  - export REGISTRY_FULL=registry.gitlab.com/notch8/ror-site/$CI_COMMIT_REF_SLUG:${CI_COMMIT_SHA:0:8}
  - export TAG=$CI_COMMIT_REF_SLUG
  - eval $(ssh-agent -s)
  - bash
  - ssh-add <(echo "$SSH_PRIVATE_KEY") 
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

review:
  stage: review
  type: deploy
  environment:
    name: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    url: http://web.$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.staging.$SITE_URI_BASE
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=staging
    - export TAG=$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    - ./rancher-v0.4.1/rancher up -p -d -u -c -s $TAG -f docker-compose-ci.yml

 tags:
    - docker

stop_review:
  stage: review
  script:

  when: manual
  environment:
    name: $CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    action: stop

staging:
  stage: staging
  type: deploy
  script:
    - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
    - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
    - export RANCHER_ENVIRONMENT=staging
    - export TAG=$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
    - ./rancher-v0.4.1/rancher up -p -d -u -c -f docker-compose-ci.yml --stack $CI_PROJECT_NAME-$CI_BUILD_REF_SLUG
  only:
    - master
  tags:
    - docker

production:
  stage: production
  type: deploy
  script:
    script:
      - wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz
      - tar zxfv rancher-linux-amd64-v0.4.1.tar.gz
      - export RANCHER_ENVIRONMENT=production
      - export TAG=goldenseal-docs-master
      - export SITE_URI=goldenseal-docs.notch8.com
      - ./rancher-v0.4.1/rancher up -p -d -u -c -f docker-compose.production.yml

  when: manual
  only:
    - master
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker
